1. Create a Python list that stores temperature of 10 consecutive days measured in degree Celcius. convert this into a Numpy array.

In [1]:
import numpy as np

# Create a Python list of temperatures for 10 consecutive days
temperature_list = [28.5, 30.2, 31.8, 29.5, 27.4, 26.7, 28.9, 29.1, 30.5, 32.0]

# Convert the list into a NumPy array
temperature_array = np.array(temperature_list)

print("Temperature list:", temperature_list)
print("Temperature array:", temperature_array)

Temperature list: [28.5, 30.2, 31.8, 29.5, 27.4, 26.7, 28.9, 29.1, 30.5, 32.0]
Temperature array: [28.5 30.2 31.8 29.5 27.4 26.7 28.9 29.1 30.5 32. ]


2. Create a Numpy array containing multiples of 3 in the range 1 to 100.

In [2]:
import numpy as np

# Create a NumPy array containing multiples of 3
multiples_of_3 = np.arange(3, 101, 3)

print("Multiples of 3 array:", multiples_of_3)

Multiples of 3 array: [ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


3. Create a Numpy array containing 10 evenly spaced values from 100 to 105.

In [3]:
import numpy as np

# Create a NumPy array with 10 evenly spaced values from 100 to 105
evenly_spaced_array = np.linspace(100, 105, 10)

print("Evenly spaced array:", evenly_spaced_array)

Evenly spaced array: [100.         100.55555556 101.11111111 101.66666667 102.22222222
 102.77777778 103.33333333 103.88888889 104.44444444 105.        ]


4. Create a 4*3 Numpy array filled with value 3.9.

In [4]:
import numpy as np

# Create a 4x3 NumPy array filled with the value 3.9
filled_array = np.full((4, 3), 3.9)

print("Filled array:\n", filled_array)

Filled array:
 [[3.9 3.9 3.9]
 [3.9 3.9 3.9]
 [3.9 3.9 3.9]
 [3.9 3.9 3.9]]


5. Create a 5*5 Numpy array filled with random values.

In [5]:
import numpy as np

# Create a 5x5 NumPy array filled with random values
random_array = np.random.rand(5, 5)

print("Random array:\n", random_array)

Random array:
 [[0.22723372 0.82771483 0.15801421 0.63732631 0.32875927]
 [0.07093499 0.36487212 0.24802412 0.48312778 0.21684207]
 [0.63489202 0.75439799 0.72364495 0.2758758  0.25850354]
 [0.58242097 0.82778178 0.74243004 0.32280464 0.33269386]
 [0.70891683 0.00142111 0.8467669  0.49793422 0.93770101]]


6. Create a two-dimensional array and print its attributes.

In [6]:
import numpy as np

# Create a 2D NumPy array (3x4)
two_dimensional_array = np.array([[1, 2, 3, 4],
                                  [5, 6, 7, 8],
                                  [9, 10, 11, 12]])

# Print array attributes
print("Array:")
print(two_dimensional_array)

print("\nAttributes:")
print("Shape:", two_dimensional_array.shape)
print("Dimensions:", two_dimensional_array.ndim)
print("Size:", two_dimensional_array.size)
print("Data Type:", two_dimensional_array.dtype)

Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Attributes:
Shape: (3, 4)
Dimensions: 2
Size: 12
Data Type: int32


7. Create an array of students enrolled in Arts, Dance, and Music activities. Form a single array containing a list of all the students.

In [7]:
import numpy as np

# Arrays of students enrolled in different activities
arts_students = np.array(['Alice', 'Bob', 'Carol'])
dance_students = np.array(['David', 'Eve', 'Frank'])
music_students = np.array(['Grace', 'Henry', 'Isabel'])

# Combine all arrays into a single array
all_students = np.concatenate((arts_students, dance_students, music_students))

print("All students:", all_students)

All students: ['Alice' 'Bob' 'Carol' 'David' 'Eve' 'Frank' 'Grace' 'Henry' 'Isabel']


8. Create an array storing marks obtained by 5 students in 4 different subjects.

* Find the highest marks obtained in each subject.
* Print the minimum marks obtained by each student
* Insert marks of one more student in this array.
* Insert marks of one more subject in the array.
* Delete a specific row from this array.
* Delete a user specified column from this array.

In [2]:
import numpy as np

# Create an array of marks obtained by 5 students in 4 subjects
marks_array = np.array([[85, 90, 78, 92],
                        [75, 88, 92, 85],
                        [92, 85, 88, 79],
                        [68, 75, 82, 90],
                        [95, 89, 78, 88]])

# Find the highest marks obtained in each subject
highest_marks_per_subject = np.max(marks_array, axis=0)
print("Highest marks per subject:", highest_marks_per_subject)

# Find the minimum marks obtained by each student
minimum_marks_per_student = np.min(marks_array, axis=1)
print("Minimum marks per student:", minimum_marks_per_student)

# Insert marks of one more student
new_student_marks = np.array([82, 78, 88, 90])
if new_student_marks.shape == marks_array.shape[1:]:
    marks_array = np.vstack((marks_array, new_student_marks))
    print("Array after adding a new student's marks:\n", marks_array)
else:
    print("New student marks shape doesn't match existing data shape")

# Insert marks of one more subject
new_subject_marks = np.array([91, 83, 78, 94, 88])
if new_subject_marks.shape[0] == marks_array.shape[0]:
    marks_array = np.column_stack((marks_array, new_subject_marks))
    print("Array after adding a new subject's marks:\n", marks_array)
else:
    print("New subject marks shape doesn't match existing data shape")

# Delete a specific row (e.g., 2nd row)
row_to_delete = 2
marks_array = np.delete(marks_array, row_to_delete, axis=0)
print("Array after deleting a row:\n", marks_array)

# Delete a user-specified column (e.g., 3rd column)
column_to_delete = 2
marks_array = np.delete(marks_array, column_to_delete, axis=1)
print("Array after deleting a column:\n", marks_array)


Highest marks per subject: [95 90 92 92]
Minimum marks per student: [78 75 79 68 78]
Array after adding a new student's marks:
 [[85 90 78 92]
 [75 88 92 85]
 [92 85 88 79]
 [68 75 82 90]
 [95 89 78 88]
 [82 78 88 90]]
New subject marks shape doesn't match existing data shape
Array after deleting a row:
 [[85 90 78 92]
 [75 88 92 85]
 [68 75 82 90]
 [95 89 78 88]
 [82 78 88 90]]
Array after deleting a column:
 [[85 90 92]
 [75 88 85]
 [68 75 90]
 [95 89 88]
 [82 78 90]]


9. Create a 3D array and print elements at even columns and odd row index.

In [3]:
import numpy as np

# Create a 3D NumPy array (3x4x5)
array_3d = np.array([[[1, 2, 3, 4, 5],
                      [6, 7, 8, 9, 10],
                      [11, 12, 13, 14, 15],
                      [16, 17, 18, 19, 20]],
                     
                     [[21, 22, 23, 24, 25],
                      [26, 27, 28, 29, 30],
                      [31, 32, 33, 34, 35],
                      [36, 37, 38, 39, 40]],
                     
                     [[41, 42, 43, 44, 45],
                      [46, 47, 48, 49, 50],
                      [51, 52, 53, 54, 55],
                      [56, 57, 58, 59, 60]]])

# Print elements at even columns and odd row indices
even_columns = array_3d[:, :, ::2]  # Slicing for even columns
odd_rows_even_columns = even_columns[:, 1::2, :]  # Slicing for odd row indices

print("Elements at even columns and odd row indices:")
print(odd_rows_even_columns)

Elements at even columns and odd row indices:
[[[ 6  8 10]
  [16 18 20]]

 [[26 28 30]
  [36 38 40]]

 [[46 48 50]
  [56 58 60]]]


10. Write a program that prints the first column elements of a 2D array.

In [4]:
import numpy as np

# Create a 2D NumPy array (4x3)
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9],
                     [10, 11, 12]])

# Get the first column elements
first_column = array_2d[:, 0]

# Print the first column elements
print("First column elements:", first_column)

First column elements: [ 1  4  7 10]


11. Write a program that creates an array from a tuple and vice versa.

In [5]:
import numpy as np

# Create a tuple
original_tuple = (1, 2, 3, 4, 5)

# Convert tuple to a NumPy array
array_from_tuple = np.array(original_tuple)

print("Tuple:", original_tuple)
print("Array from tuple:", array_from_tuple)

# Convert NumPy array back to a tuple
tuple_from_array = tuple(array_from_tuple)

print("Tuple from array:", tuple_from_array)

Tuple: (1, 2, 3, 4, 5)
Array from tuple: [1 2 3 4 5]
Tuple from array: (1, 2, 3, 4, 5)


12. Create a program that converts a 1D array into 3D array and vice versa.

In [6]:
import numpy as np

# Create a 1D NumPy array
original_1d_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Convert 1D array to a 3D array (2x3x2)
reshaped_3d_array = original_1d_array.reshape(2, 3, 2)

print("Original 1D array:", original_1d_array)
print("Reshaped 3D array:")
print(reshaped_3d_array)

# Convert 3D array back to a 1D array
flattened_1d_array = reshaped_3d_array.flatten()

print("Flattened 1D array:", flattened_1d_array)

Original 1D array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped 3D array:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Flattened 1D array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


13. Write a program that prints the cube of odd numbers in the array.

In [7]:
import numpy as np

# Create a NumPy array
num_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Find odd numbers and print their cubes
odd_numbers = num_array[num_array % 2 != 0]
odd_cubes = odd_numbers ** 3

print("Odd numbers:", odd_numbers)
print("Cubes of odd numbers:", odd_cubes)

Odd numbers: [1 3 5 7 9]
Cubes of odd numbers: [  1  27 125 343 729]


14. Write a program that sums the columns of a 2D array and prints the columns whose sum is divisible by 5.

In [8]:
import numpy as np

# Create a 2D NumPy array (4x3)
array_2d = np.array([[10, 15, 5],
                     [3, 8, 12],
                     [7, 6, 9],
                     [2, 5, 8]])

# Sum the columns of the 2D array
column_sums = np.sum(array_2d, axis=0)

print("Column sums:", column_sums)

# Find and print columns whose sum is divisible by 5
divisible_by_5_columns = np.where(column_sums % 5 == 0)[0]

print("Columns whose sum is divisible by 5:", divisible_by_5_columns)

Column sums: [22 34 34]
Columns whose sum is divisible by 5: []


15. Write a program that prints the sum of columns of a 3D array.

In [9]:
import numpy as np

# Create a 3D NumPy array (2x3x4)
array_3d = np.array([[[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]],
                     
                     [[13, 14, 15, 16],
                      [17, 18, 19, 20],
                      [21, 22, 23, 24]]])

# Sum the columns of the 3D array
column_sums = np.sum(array_3d, axis=(0, 1))  # Sum along both rows and depth

print("Column sums:", column_sums)

Column sums: [66 72 78 84]


16. Convert a 1D array with 12 elements into a 2-D array. The outermost dimension will have 4 arrays, each with 3 elements.

In [10]:
import numpy as np

# Create a 1D NumPy array with 12 elements
original_1d_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Reshape the 1D array into a 2D array (4x3)
reshaped_2d_array = original_1d_array.reshape(4, 3)

print("Original 1D array:")
print(original_1d_array)

print("\nReshaped 2D array:")
print(reshaped_2d_array)

Original 1D array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped 2D array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


17. Create a 3D array with only one 2D array as its element. Reduce dimension of this array and print the resultant array.

In [11]:
import numpy as np

# Create a 3D NumPy array with a single 2D array element (1x3x4)
array_3d = np.array([[[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]]])

# Reduce the dimensions to a 2D array
reduced_2d_array = array_3d[0]

print("Original 3D array:")
print(array_3d)

print("\nReduced 2D array:")
print(reduced_2d_array)

Original 3D array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]

Reduced 2D array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
