### Importing the Array Module

In [1]:
#A python program to create an integer type array.
#Creating an array.
import array
a = array.array('i',[5, 6, -7, 8])

print("The array elements are: ")
for element in a:
    print(element)

The array elements are: 
5
6
-7
8


In [2]:
#A python program to create an integer type array.
#Creating an array 
from array import *
a = array('i', [5, 6, -7, 8])

print("The array elements are: ")
for element in a:
    print(element)

The array elements are: 
5
6
-7
8


In [4]:
#A Python program to create an array with a group of characters.
#Creating an array with characters
from array import *
arr = array('u',['a', 'b', 'c', 'd', 'e'])

print("The elements are: ")
for ch in arr:
    print(ch)

The elements are: 
a
b
c
d
e


In [5]:
#A python program to crate one array from another array.
#Creating one array from another array
from array import *
arr1 = array('d', [1.5, 2.5, -3.5, 4])

#use same type code and multiply each element of arr1 with 3
arr2 = array(arr1.typecode, (a*3 for a in arr1))
print("The arr2 elements are: ")
for i in arr2:
    print(i)

The arr2 elements are: 
4.5
7.5
-10.5
12.0


### Indexing and Slicing on Arrays

In [6]:
#A python program to retrieve the elements of an array using array index.
#accesing elements of an array using index.
from array import *
x = array('i', [10, 20, 30, 40, 50])

#find number of elements in the array
n = len(x)

#display array elements using indexing
for i in range(n): #repeat from 0 to n-1
    print(x[i], end = " ")

10 20 30 40 50 

In [1]:
#A python program to retrieve elements of an array using while loop.
#accessing elements of an array using index.
from array import *
x = array('i', [10, 20, 30, 40, 50])

#find number of elements in the array
n = len(x)

#display array elements using indexing
i = 0
while i < n:
    print(x[i], end = " ")
    i+=1

10 20 30 40 50 

In [11]:
#A python program to retrieve and display only a range of elements from an array using slicing.
#using slicing to display elements of an array.
from array import *
x = array('i', [10, 20, 30, 40, 50, 60, 70])

#display elements from 2nd to 4th only.
for i in x[2:5]:
    print(i)

30
40
50


### Processing the Arrays

In [2]:
#A python program to understand various methods of arrays class.
#Operations on arrays
from array import *

#Create an array with int values
arr = array('i', [10, 20, 30, 40, 50])
print('Original array: ', arr) 

#append 30 to the array arr
arr.append(30)
arr.append(60)
print("After appending 30 and 60: ", arr)

#Insert 99 at position number 1 in arr
arr.insert(1, 99)
print("After inserting 99 in 1st position: ", arr)

#remove an element from arr
arr.remove(20)
print("After removing 20: ", arr)

#remove last element using pop() method
n = arr.pop()
print("Array after using pop(): ", arr)
print("popped element: ", n)

#finding position of element using index() method
n = arr.index(30)
print("First occurence of a element 30 is at: ", n)

#convert an array into a list using tolist() method
lst = arr.tolist()
print("List: ", lst)
print("Array: ", arr)

Original array:  array('i', [10, 20, 30, 40, 50])
After appending 30 and 60:  array('i', [10, 20, 30, 40, 50, 30, 60])
After inserting 99 in 1st position:  array('i', [10, 99, 20, 30, 40, 50, 30, 60])
After removing 20:  array('i', [10, 99, 30, 40, 50, 30, 60])
Array after using pop():  array('i', [10, 99, 30, 40, 50, 30])
popped element:  60
First occurence of a element 30 is at:  2
List:  [10, 99, 30, 40, 50, 30]
Array:  array('i', [10, 99, 30, 40, 50, 30])


In [1]:
#A python program to sorting student's marks into an array and finding total marks and percentage of marks.
from array import *
#accept marks from keyboard into a list
lst = [int(i) for i in input("Enter marks: ").split(',')]
#Create an integer array from the above list
marks = array('i', lst)

#display the marks and find total
sum = 0
for x in marks:
    print(x)
    sum = sum+x
print("Total marks: ", sum)

#display percentage
n = len(marks) #no of elements in marks array
percent = sum/n
print("Percentage: ", percent)

Enter marks: 50, 60, 70, 80, 90
50
60
70
80
90
Total marks:  350
Percentage:  70.0


In [4]:
#A python program to sort the array elements using bubble sort technique.
#Sorting an array using Bubble sort technique
from array import *
#Create an empty array to store integers
x = array('i', [])

#store elements into the array x
print("How many elements? ", end = "")
n = int(input()) #accpet input into n

for i in range(n): #repeat for n times
    print("Enter element: ", end = "")
    x.append(int(input())) #add the element to the array x
print("Original array: ", x)

#bubble sort
flag = False #When swapping is done, flag becomes true
for i in range(n-1): #i is from 0 to n-1
    for j in range(n-1-i): #i is from 0 to one element lesser than i
        t = x[j] #swap j and j+1 elements
        x[j] = x[j+1]
        x[j+1] = t
        flag = True #swapping done, hence flag is true
    if flag == False: #no swapping means array is in sorted order
        break #come out of inner for loop
    else:
        flag = False #assign initial value flag
        
print("Sorted array= ", x)

How many elements? 5
Enter element: 1
Enter element: 5
Enter element: 4
Enter element: 3
Enter element: 2
Original array:  array('i', [1, 5, 4, 3, 2])
Sorted array=  array('i', [2, 3, 4, 5, 1])


In [6]:
#A python program to search for the position of an element in an array using sequential search.
#searchin an array for an element.
from array import *
#Create an empty array to store integers
x = array('i', [])

#store elements into the array x
print("How many elements? ", end = "")
n = int(input()) #accept input into n

for i in range(n): #repeat for n times
    print("Enter element: ", end = "")
    x.append(int(input())) #add the element to the array x
    
print("Original array: ", x)
print("Enter element to search: ", end = "")
s = int(input()) #accept element to be searched

#linear search or sepuential search
flag = False #this becomes True if element is found

for i in range(len(x)): #repeat i from 0 to no. of elements
    if s == x[i]:
        print("Found at position= ", i+1)
        flag = True
if flag == False:
    print("Not found in the array")

How many elements? 5
Enter element: 5
Enter element: 20
Enter element: 40
Enter element: 20
Enter element: 55
Original array:  array('i', [5, 20, 40, 20, 55])
Enter element to search: 20
Found at position=  2
Found at position=  4


In [7]:
#A python program to search for the position of an element in an array using index() method.
#Searching an array for an element
from array import *
#create an empty array to store integers
x = array('i', [])

#store elements into the array x
print("How many element? ", end = "")
n = int(input()) #accept input into n

for i in range(n): #repeat for n times.
    print("Enter element: ", end = "")
    x.append(int(input())) #add the element to the array x
    
print("Original array: ", x)

print("Enter element to search: ", end = "")
s = int(input()) #accept element to be searched

#index() method gives the location of the element in the array
try:
    pos = x.index(s)
    print("Found at position= ", pos+1)
    
except ValueError: #if element not found then ValueError will rise
    print("Not found in the array")

How many element? 5
Enter element: 20
Enter element: 40
Enter element: 50
Enter element: 20
Enter element: 10
Original array:  array('i', [20, 40, 50, 20, 10])
Enter element to search: 20
Found at position=  1


### Working with Arrays using numpy

In [8]:
#A python program to create a simple array using numpy.
#Creating single dimensional array using numpy.
import numpy
arr = numpy.array([10, 20, 30, 40, 50]) #create array
print(arr) #display array

[10 20 30 40 50]


In [9]:
#Another version of above program to create an array.
#Creating single dimensional array using numpy.
import numpy as np
arr = np.array([10, 20, 30, 40, 50]) #Create array
print(arr) #display array

[10 20 30 40 50]


In [10]:
#Another version of above program to create an array
#Creating single dimensional array using numpy.
from numpy import *
arr = array([10, 20, 30, 40, 50]) #create array
print(arr) #display array

[10 20 30 40 50]


### Creating Arrays using array()

In [11]:
#A python program to create a character type array with a group of characters.
#Creating an array with characters
from numpy import *
arr = array(['a', 'b', 'c', 'd']) #create array
print(arr)

['a' 'b' 'c' 'd']


In [12]:
#A python program to create a string type array using numpy
#Creating an array with characters
from numpy import *

#Create array
arr = array(['Delhi', 'Hyderabad', 'Mumbai', 'Ahmedabad'], dtype = str)
print(arr) #display array

['Delhi' 'Hyderabad' 'Mumbai' 'Ahmedabad']


In [13]:
#A python program to create an array from another array.
#Creating an array feom another array.
from numpy import *
a = array([1, 2, 3, 4, 5]) #original array
b = array(a) #Create b from a using array() function
c = a #create c by assigning a to c

#Display the arrays
print("a= ", a)
print("b= ", b)
print("c= ", c)

a=  [1 2 3 4 5]
b=  [1 2 3 4 5]
c=  [1 2 3 4 5]


### Creating Arrays using linspace

In [14]:
#A python program to creating an array with 5 equal points using linspace
#Creating an array using linspace()
from numpy import *

#Divide 0 to 10 into 5 parts and take those points in the array
a = linspace(0, 10, 5)
print("a= ", a)

a=  [ 0.   2.5  5.   7.5 10. ]


### Creating Arrays using logspace

In [15]:
#A python program to create an array using logspace()
#Creating an array using logspace()
from numpy import *

#Divide the range: 10 power 1 to 10 power 4 into 5 equal parts
#and take those points in the array
a = logspace(1, 4, 5)

#find no. of element in a
n = len(a)

#repeat from  0 to n-1 times
for i in range(n):
    print('%.1f' % a[i], end = " ") #display 1 digit after decimal point

10.0 56.2 316.2 1778.3 10000.0 

### Creating Arrays using arrange() Function

In [16]:
#A python program to create an array with even numbers up to 10.
#Creating an array with even numbers up to 10
from numpy import *

#Create an array using array() function
a = arange(2, 11, 2)
print(a)

[ 2  4  6  8 10]


### Creating Arrays using Zeros() and ones() Function

In [17]:
#A python program to create arrays using zeros() and ones().
#Creating arrays using zeros() and ones()
from numpy import *

a = zeros(5, int)
print(a)

b = ones(5) #default datatype is float
print(b)

[0 0 0 0 0]
[1. 1. 1. 1. 1.]


### Mathematical Operations on Arrays

In [19]:
#A python program to perform some mathematical operations on a numpy array.
#mathematical operations on arrays
#import all from numpy module
from numpy import *

#Create a numpy array using array() function
arr = array([10, 20, 30.5, -40])
print("Original array: ", arr)

#do arithmatic operations on the elements of the array.
print("After adding 5: ", arr+5)
print("After subtracting 5: ", arr-5)
print("After multiplying with 5: ", arr*5)
print("After dividing with 5: ", arr/5)
print("After modulus with 5: ", arr%5)

#we can use the arrays in expressions also
print("Expression value: ", (arr+5)**2-10)

#Do some math functions
print("Sin values: ", sin(arr))
print("Cos values: ", cos(arr))
print("Tan values: ", tan(arr))
print("Biggest element: ", max(arr))
print("Smallest element: ", min(arr))
print("Sum of all element: ", sum(arr))
print("Average of all elements: ", mean(arr))

Original array:  [ 10.   20.   30.5 -40. ]
After adding 5:  [ 15.   25.   35.5 -35. ]
After subtracting 5:  [  5.   15.   25.5 -45. ]
After multiplying with 5:  [  50.   100.   152.5 -200. ]
After dividing with 5:  [ 2.   4.   6.1 -8. ]
After modulus with 5:  [0.  0.  0.5 0. ]
Expression value:  [ 215.    615.   1250.25 1215.  ]
Sin values:  [-0.54402111  0.91294525 -0.79312724 -0.74511316]
Cos values:  [-0.83907153  0.40808206  0.60905598 -0.66693806]
Tan values:  [ 0.64836083  2.23716094 -1.30222389  1.11721493]
Biggest element:  30.5
Smallest element:  -40.0
Sum of all element:  20.5
Average of all elements:  5.125


### Comparing Arrays

In [20]:
#A python program to compare two arrays and display the resultant Boolean type array.
#To know the result of comparing two arrays
from  numpy import *
a = array([1, 2, 3, 0])
b = array([0, 2, 3, 1])

c = a == b
print("Result of a==b: ", c)
c = a > b
print("Result of a>b: ", c)
c = a <= b
print("Result of a <= b: ", c)

Result of a==b:  [False  True  True False]
Result of a>b:  [ True False False False]
Result of a <= b:  [False  True  True  True]


In [21]:
#A python program to know the effect of any() and all() functions
#using any() and all() functions
from numpy import *
a = array([1, 2, 3, 0])
b = array([0, 2, 3, 1])

c = a > b
print("Result of a>b: ", c)

print("Check if any one element is true: ", any(c))
print("Check if all elements are true: ", all(c))

if (any(a>b)):
    print('a contains atleast one element greater than those of b')

Result of a>b:  [ True False False False]
Check if any one element is true:  True
Check if all elements are true:  False
a contains atleast one element greater than those of b


In [22]:
#A python program to understand the use of logical functions on arrays.
#using logical_and(), logical_or(), logical_not()
from numpy import *
a = array([1, 2, 3], int)
b = array([0, 2, 3], int)

c = logical_and(a>0, a<4)
print(c)

c = logical_or(b>=0, b == 1)
print(c)

c = logical_not(b)
print(c)

[ True  True  True]
[ True  True  True]
[ True False False]


In [23]:
#A python program to compare the corresponding elements of two arrays and retrieve the biggest elements.
#using where() function.
from numpy import *
a = array([10, 20, 30, 40, 50], int)
b = array([1, 21, 3, 40, 51], int)
#if a>b then take element from a else from b
c = where(a>b, a, b)
print(c)

[10 21 30 40 51]


In [24]:
#A python program to retrieve non zero elements from an array.
#using nonzero() function.
from numpy import *
a = array([1, 2, 0, -1, 0, 6], int)

#retrieves indexes of non zero elements from a
c = nonzero(a)

#display indexes
for i in c:
    print(i)
    
#display the elements
print(a[c])

[0 1 3 5]
[ 1  2 -1  6]


### Aliasing the Arrays

In [25]:
#A python program to alias an array and undestand the effect of aliasing.
#aliasing an array
from numpy import *

a = arange(1, 6) #create a with elements 1 to 5.
b = a #give another name b to a

print("Original array: ", a)
print("Alias array: ", b)

b[0] = 99 #modify the element of b
print("After modification: ")
print("Original array: ", a)
print("Alias array: ", a)

Original array:  [1 2 3 4 5]
Alias array:  [1 2 3 4 5]
After modification: 
Original array:  [99  2  3  4  5]
Alias array:  [99  2  3  4  5]


### Viewing and Copying Arrays

In [26]:
#A python program to create a view of an existing array.
#Creating view for an array
from numpy import *

a = arange(1, 6) #Create a with element 1 to 5.
b = a.view() #create a view of a and call it b.
print("Original array: ", a)
print("New array: ", b)

b[0] = 99 #modify 0th element of b

print("After modification: ")
print("Original array: ", a)
print("New array: ", b)

Original array:  [1 2 3 4 5]
New array:  [1 2 3 4 5]
After modification: 
Original array:  [99  2  3  4  5]
New array:  [99  2  3  4  5]


In [27]:
#A python program to copy an array as another array.
#copying an array
from numpy import *

a = arange(1, 6) #create a with elements 1 to 5.
b = a.copy() #create a copy of a and call it b.

print("Original array: ", a)
print("New array: ", b)

b[0] = 99 #modify 0th element b

print("After modification: ")
print("Original array: ", a)
print("New array: ", b)

Original array:  [1 2 3 4 5]
New array:  [1 2 3 4 5]
After modification: 
Original array:  [1 2 3 4 5]
New array:  [99  2  3  4  5]


### Slicing and Indexing in numpy Arrays

In [28]:
#A python program to understand slicing operations on arrays. 
#slicing an array
from numpy import *
#Create array a with elements 10 to 15.
a = arange(10, 16)
print(a)

#retrieve from 1st to one element prior to 6th element in steps of 2
b = a[1:6:2]
print(b)

#retrieve all elements from a 
b = a[::]
print(b)

#retrieve from 6-2 = 4th to one element prior to 2nd element in decreasing step size.
b = a[-2:2:-1]
print(b)

#retrieve from 0th to one element prior to 4th element (6-2= 4th)
b = a[:-2:]
print(b)

[10 11 12 13 14 15]
[11 13 15]
[10 11 12 13 14 15]
[14 13]
[10 11 12 13]


In [50]:
#A Python program to retieve and display elements of a numpy array using indexing.
#indexing an array
from numpy import*
#create array a with elements 10 to 15.
a = arange(10, 15)
print(a)
#retrieve from 1st to one element prior to 6th element in steps of 2
a = a[1:6:2]
print(a)

#display elements using indexing
i = 0
while (i < len(a)):
    print(a[i])
    i += 1

[10 11 12 13 14]
[11 13]
11
13


### Indexing in Multi-dimensional Arrays

In [31]:
#A python program to retrieve the elements from a 2D array and display them using for loops.
#retrieving the elements from a 2D array using indexing
from numpy import *

#create a 2D array with 3 rows and 3 cols
a = [[1,2,3], [4, 5, 6], [7, 8, 9]]

#display only rows
for i in range(len(a)):
    print(a[i])
    
#display element by element
for i in range(len(a)):
    for j in range(len(a[i])):
        print(a[i][j], end=' ')

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
1 2 3 4 5 6 7 8 9 

In [32]:
#A python program to retrieve the elements from a 3D array.
#Retrieving the elements from a 3D array using indexing.
from numpy import *
#Create a 3D arrray with size 2*2*3
a = [[[1,2,3],
    [4,5,6]],

    [[7,8,9],
    [10,11,12]]]

#display element by element
for i in range(len(a)):
    for j in range(len(a[i])):
        for k in range(len(a[i][j])):
            print(a[i][j][k], end='\t')
        print()
    print()

1	2	3	
4	5	6	

7	8	9	
10	11	12	



### Transpose of a Matrix

In [33]:
#A python program to accept a matrix from the keyboard and display its transpose matrix.
#transpose of a matrix
from numpy import *

#accept number of rows and cols into r, c
r, c = [int(a) for a in input("Enter rows, cols: ").split()]

#accept matrix elements as a string into str
str = input("Enter matrix elements:\n ")

#convert the string into a matrix with size r*c
x = reshape(matrix(str), (r, c))
print("The original matrix: ")
print(x)

print("The transpose matrix: ")
y = x.transpose()
print(y)

Enter rows, cols: 2 3
Enter matrix elements:
 1 2 3 4 5 6
The original matrix: 
[[1 2 3]
 [4 5 6]]
The transpose matrix: 
[[1 4]
 [2 5]
 [3 6]]



### Matrix Addition and Multiplication

In [34]:
#A python program to accept two matrices and find their product.
#matrix multiplication
import sys
from numpy import *

#accept number of rows and cols of first matrix into r1, c1
r1, c1 = [int(a) for a in input("First matrix rows, cols: ").split()]

#accept number of rows and cols of second matrix r2, c2
r2, c2 = [int(a) for a in input("Second matrix rows, cols: ").split()]

#test the condition if c1 != r2, then multiplication is not possible
if c1 != r2:
    print("Multiplication is not possible")
    sys.exit() #terminate the program
    
#accept first matrix elements as a string into str1
str1 = input("Enter first matrix elements:\n ")

#Convert str1 into a matrix with size r1*c1
x = reshape(matrix(str1), (r1, c1))

#accept second matrix elements as a string into str2
str2 = input("Enter second matrix elements:\n ")

#convert str2 into a matrix with size r2*c2
y = reshape(matrix(str2), (r2, c2))
print("The product matrix: ")
z = x*y
print(z)

First matrix rows, cols: 2 3
Second matrix rows, cols: 3 2
Enter first matrix elements:
 1 2 3 4 5 6
Enter second matrix elements:
 1 0 0 2 1 -1
The product matrix: 
[[ 4  1]
 [10  4]]


In [ ]:
#A python program to accept two matrices and find their product.
#matrix multiplication
import sys
from numpy import *

#accept number of rows and cols of first matrix into r1, c1
r1, c1 = [int(a) for a in input("First matrix rows, cols: ").split()]

#accept number of rows and cols of second matrix r2, c2
r2, c2 = [int(a) for a in input("Second matrix rows, cols: ").split()]

#test the condition if c1 != r2, then multiplication is not possible
if c1 != r2:
    print("Multiplication is not possible")
    sys.exit() #terminate the program
    
#accept first matrix elements as a string into str1
str1 = input("Enter first matrix elements:\n ")

#Convert str1 into a matrix with size r1*c1
x = reshape(matrix(str1), (r1, c1))

#accept second matrix elements as a string into str2
str2 = input("Enter second matrix elements:\n ")

#convert str2 into a matrix with size r2*c2
y = reshape(matrix(str2), (r2, c2))
print("The product matrix: ")
z = x*y
print(z)